### ISSUE TITLE
"npm install -g generator-addon-library" not working

### ISSUE THREAD

**Issue by joboyx** [ngx-rocket/addon-library#1]
looks like `generator-addon-library` is not in npm registry

![image](https://user-images.githubusercontent.com/920888/102475012-4dd3dd80-4094-11eb-8a85-28b1875f7cc1.png)

**Comment by sinedied** [comment]
> WIP: this add-on has not been published yet

😉 

This addon was started way before `ng generate library` was available, and it won't be finished as some blocking issues were never solved upstream. You should use the `ng` CLI for that now.

I'll update the readme and repo to clarify the status.
